// Curriculum is the single source of truth for lesson content and grading contracts.
const test = (name, expression, expected) => ({ name, expression, expected });
const lesson = (
  id,
  title,
  concept,
  example,
  task,
  starter,
  solution,
  tests,
  types = '',
  negative = [],
  hints = [],
) => ({
  id,
  title,
  concept,
  example,
  task,
  starter,
  solution,
  tests,
  types,
  negative,
  hints: hints.length ? hints : [concept, example],
  requirements: tests.map((t) => t.name),
});
export const chapters = [
  {
    title: 'JavaScript 必要語法',
    subtitle: '熟悉的邏輯，新的表達方式。',
    comparisons: {
      'C++':
        'let 類似可重新賦值的 auto；const 限制 binding，並不等同 C++ 的深層唯讀語意。number 是雙精度浮點數，沒有 int / float 的型別區分。',
      'C#': 'let 的推導類似 var。TS const 是不可重新綁定，不等同 C# 編譯期常數。型別註記編譯後會消失。',
      Python:
        'TS 會在執行前檢查型別；變數一旦推導為 number，就不能再放入字串。使用 let 宣告可變 binding、const 宣告固定 binding。',
    },
    lessons: [
      lesson(
        '01-01',
        '宣告與型別推導',
        '用 let 宣告會重新賦值的變數，const 宣告固定的 binding。冒號後是型別註記。TypeScript 的型別只存在於檢查階段；執行的是 JavaScript。',
        'let count: number = 3;\nconst language = "TypeScript";',
        '修正 count 的宣告與型別，累加一次。將 message 設為 "Total: 4"，印出結果。',
        'const count: string = 3;\ncount += 1;\nconst message = "";\nconsole.log(message);',
        'let count: number = 3;\ncount += 1;\nconst message = `Total: ${count}`;\nconsole.log(message);',
        [
          test('count 是數值 4', 'count', 4),
          test('message 是 "Total: 4"', 'message', 'Total: 4'),
        ],
        'type C = Expect<Equal<typeof count, number>>;',
      ),
      lesson(
        '01-02',
        '字串模板',
        '使用反引號建立 template literal，${expression} 可以插入運算式。函式參數用 name: type 標註。',
        'const who = "Michael";\nconst text = `Hello, ${who}!`;',
        '完成 greet(name, count)，回傳 "Hi Michael, 3 tasks" 這樣的字串。',
        'function greet(name: string, count: number): string {\n  return "";\n}',
        'function greet(name: string, count: number): string {\n  return `Hi ${name}, ${count} tasks`;\n}',
        [
          test('插入名稱和數值', 'greet("Michael", 3)', 'Hi Michael, 3 tasks'),
          test('可處理其他輸入', 'greet("Ada", 0)', 'Hi Ada, 0 tasks'),
        ],
      ),
      lesson(
        '01-03',
        '空值與預設值',
        'undefined 常表示未提供，null 表示明確的空值。?? 只對這兩種值使用預設值；|| 還會把 0、false、空字串視為需要替代。',
        'const pageSize = input ?? 20;',
        '完成 label，空值回傳 "Guest"，但保留空字串。',
        'function label(value: string | null | undefined): string {\n  return "Guest";\n}',
        'function label(value: string | null | undefined): string {\n  return value ?? "Guest";\n}',
        [
          test('null 使用預設值', 'label(null)', 'Guest'),
          test('undefined 使用預設值', 'label(undefined)', 'Guest'),
          test('保留空字串', 'label("")', ''),
          test('保留一般字串', 'label("Michael")', 'Michael'),
        ],
      ),
      lesson(
        '01-04',
        '嚴格相等',
        '=== 不會先做型別轉換。避免把數字 0 與字串 "0" 混為一談。用 typeof 觀察執行時型別。',
        '0 === 0; // true\ntypeof "0"; // "string"',
        '完成 isZero，只有數字 0 才回傳 true。',
        'function isZero(value: number | string): boolean {\n  return true;\n}',
        'function isZero(value: number | string): boolean {\n  return value === 0;\n}',
        [
          test('數字 0 通過', 'isZero(0)', true),
          test('字串 "0" 不通過', 'isZero("0")', false),
          test('空字串不通過', 'isZero("")', false),
          test('其他數字不通過', 'isZero(2)', false),
        ],
      ),
    ],
  },
  {
    title: '陣列與物件',
    subtitle: '解構、展開與安全存取。',
    comparisons: {
      'C++':
        'number[] 是動態 JS 陣列，不是固定大小 C 陣列。spread 是淺拷貝；巢狀物件仍共用參考。',
      'C#': 'map / filter 類似 Select / Where，但 JS 陣列方法通常立即求值。物件 spread 類似建立新物件並覆蓋欄位。',
      Python:
        '解構類似 unpacking，spread 類似 * / **。物件用 .name 或 [key] 存取；陣列 map / filter 常取代 comprehension。',
    },
    lessons: [
      lesson(
        '02-01',
        '陣列轉換',
        'T[] 宣告陣列元素型別。filter 保留符合條件的元素，map 產生轉換後的新陣列，不改變原陣列。',
        'const doubled = [1, 2].map(n => n * 2);',
        '完成 positiveDoubled：只保留正數，再乘以 2。',
        'function positiveDoubled(values: number[]): number[] {\n  return [];\n}',
        'function positiveDoubled(values: number[]): number[] {\n  return values.filter(n => n > 0).map(n => n * 2);\n}',
        [
          test('過濾再轉換', 'positiveDoubled([-2, 0, 1, 3])', [2, 6]),
          test('空陣列', 'positiveDoubled([])', []),
        ],
      ),
      lesson(
        '02-02',
        '物件解構',
        'const { name, age } = obj 把屬性解構成變數。屬性可以重新命名，也可以設定 undefined 時的預設值。',
        'const { name: displayName, role = "reader" } = user;',
        '完成 describe，解構 name 與 role；未提供 role 時用 "reader"。',
        'function describe(user: { name: string; role?: string }): string {\n  return "";\n}',
        'function describe(user: { name: string; role?: string }): string {\n  const { name, role = "reader" } = user;\n  return `${name}: ${role}`;\n}',
        [
          test(
            '提供角色',
            'describe({name:"Ada", role:"admin"})',
            'Ada: admin',
          ),
          test('預設角色', 'describe({name:"Lin"})', 'Lin: reader'),
        ],
      ),
      lesson(
        '02-03',
        'Spread 與 rest',
        '物件展開由左到右覆蓋同名欄位。rest 參數把剩餘引數收集為陣列；兩者共用 ... 語法，但用途不同。',
        'const next = { ...previous, enabled: true };\nconst sum = (...ns: number[]) => ns.reduce((a,b) => a+b, 0);',
        '完成 update：複製 settings，覆蓋 theme 為新值。不要修改輸入物件。',
        'function update(settings: {theme: string; size: number}, theme: string) {\n  return settings;\n}',
        'function update(settings: {theme: string; size: number}, theme: string) {\n  return { ...settings, theme };\n}',
        [
          test('覆蓋指定欄位', 'update({theme:"light",size:14}, "dark")', {
            theme: 'dark',
            size: 14,
          }),
          test(
            '原物件維持原值',
            '(()=>{const s={theme:"light",size:14}; update(s,"dark"); return s.theme;})()',
            'light',
          ),
        ],
      ),
      lesson(
        '02-04',
        'Optional chaining',
        '?. 在接收者為 null 或 undefined 時停止存取，回傳 undefined。搭配 ?? 提供預設值；不要用 ! 假裝值一定存在。',
        'const city = user.address?.city ?? "Unknown";',
        '完成 cityOf，缺少 address 或 city 時回傳 "Unknown"。',
        'function cityOf(user: {address?: {city?: string}}): string {\n  return "Unknown";\n}',
        'function cityOf(user: {address?: {city?: string}}): string {\n  return user.address?.city ?? "Unknown";\n}',
        [
          test('有城市', 'cityOf({address:{city:"Taipei"}})', 'Taipei'),
          test('沒有地址', 'cityOf({})', 'Unknown'),
          test('空城市字串保留', 'cityOf({address:{city:""}})', ''),
        ],
      ),
    ],
  },
  {
    title: '函式與 callback',
    subtitle: '讓輸入與輸出形成契約。',
    comparisons: {
      'C++':
        '箭頭函式像 lambda；TS 使用結構型函式型別表達 callback。沒有 C++ capture list，閉包依 JS 語意捕捉外部變數。',
      'C#': '(x: number) => number 類似 Func<double, double>。箭頭函式也會捕捉外部變數，且沒有自己的 this。',
      Python:
        '箭頭函式可用 expression 或 block；參數型別必須放在參數名稱後。TS 預設參數於每次呼叫時計算。',
    },
    lessons: [
      lesson(
        '03-01',
        '參數與回傳',
        '函式宣告用 function name(arg: Type): ReturnType。回傳型別可以推導；明確標註能讓不符合契約的 return 當場報錯。',
        'function double(n: number): number { return n * 2; }',
        '完成 add，接收兩個 number 並回傳它們的和。',
        'function add(a: number, b: number): number {\n  return 0;\n}',
        'function add(a: number, b: number): number {\n  return a + b;\n}',
        [test('兩正數', 'add(2, 3)', 5), test('包含負數', 'add(-3, 1)', -2)],
        '',
        ['add("2", 3);'],
      ),
      lesson(
        '03-02',
        '箭頭函式',
        '箭頭右側單一 expression 會隱含 return；改用大括號時需要明確 return。直接回傳物件 literal 時，以小括號包住物件。',
        'const make = (name: string) => ({ name });',
        '完成 makeUser 箭頭函式，回傳含 name 與 active: true 的物件。',
        'const makeUser = (name: string) => {\n  // 回傳物件\n};',
        'const makeUser = (name: string) => ({ name, active: true });',
        [
          test('建立使用者', 'makeUser("Michael")', {
            name: 'Michael',
            active: true,
          }),
        ],
      ),
      lesson(
        '03-03',
        '預設與 rest 參數',
        '預設值適用於省略引數或傳入 undefined。rest 必須是最後一個參數，型別通常為陣列。',
        'function join(prefix = "log", ...parts: string[]) {\n  return `${prefix}: ${parts.join(" ")}`;\n}',
        '完成 total，第一個參數 base 預設為 10，再加上其餘 numbers。',
        'function total(base = 10, ...numbers: number[]): number {\n  return base;\n}',
        'function total(base = 10, ...numbers: number[]): number {\n  return numbers.reduce((sum, n) => sum + n, base);\n}',
        [
          test('預設 base', 'total()', 10),
          test('多個引數', 'total(1, 2, 3)', 6),
          test('undefined 使用預設', 'total(undefined, 5)', 15),
        ],
      ),
      lesson(
        '03-04',
        '函式型別',
        '函式可作為值傳遞。型別 (value: number) => boolean 表示接收 number 並回傳 boolean，不必用額外的 class。',
        'type Predicate = (value: number) => boolean;',
        '定義 Predicate，完成 select，只保留 callback 回傳 true 的數字。',
        'type Predicate = unknown;\nfunction select(values: number[], predicate: Predicate): number[] {\n  return [];\n}',
        'type Predicate = (value: number) => boolean;\nfunction select(values: number[], predicate: Predicate): number[] {\n  return values.filter(predicate);\n}',
        [
          test('選出偶數', 'select([1,2,3,4], n => n % 2 === 0)', [2, 4]),
          test('自訂条件', 'select([1,5,9], n => n > 5)', [9]),
        ],
        'type P = Expect<Equal<Predicate, (value: number) => boolean>>;',
        ['select([1], (n: number) => "yes");'],
      ),
    ],
  },
  {
    title: '定義資料結構',
    subtitle: '用形狀描述資料。',
    comparisons: {
      'C++':
        'interface 描述 shape，不會產生執行時物件。TS 不要求宣告繼承才相容：只要結構符合即可。',
      'C#': '不像 C# nominal typing，TS interface 一般按結構判斷相容。interface 不會在執行時存在，也不能直接拿來 instanceof。',
      Python:
        '類似 TypedDict / Protocol 的靜態用途。readonly 是型別檢查的限制，不是執行時凍結。',
    },
    lessons: [
      lesson(
        '04-01',
        'Interface 與可選屬性',
        'interface 描述物件的必要欄位與可選欄位。name?: string 表示可以省略；讀取時必須處理 undefined。',
        'interface User { id: number; name: string; email?: string; }',
        '定義 User，id 為 number、name 為 string、email 可省略。完成 display，回傳 name。',
        'interface User {}\nfunction display(user: User): string {\n  return "";\n}',
        'interface User { id: number; name: string; email?: string; }\nfunction display(user: User): string { return user.name; }',
        [test('不提供 email', 'display({id:1,name:"Ada"})', 'Ada')],
        'const u: User = {id:1,name:"Ada"};\ntype U = Expect<Equal<User["id"], number>>;',
        ['const bad: User = {id:"1",name:"Ada"};', 'const bad: User = {id:1};'],
      ),
      lesson(
        '04-02',
        'Type 與 tuple',
        'type 可以命名物件、union、tuple 等型別。tuple 描述每個位置的型別，比 (string | number)[] 更精確。',
        'type Entry = [string, number];',
        '定義 Entry 為 [string, number]，完成 formatEntry，回傳 "cpu=80" 形式的字串。',
        'type Entry = [];\nfunction formatEntry(entry: Entry): string { return ""; }',
        'type Entry = [string, number];\nfunction formatEntry([key, value]: Entry): string { return `${key}=${value}`; }',
        [test('解構 tuple', 'formatEntry(["cpu",80])', 'cpu=80')],
        'type E = Expect<Equal<Entry, [string, number]>>;',
        ['const bad: Entry = [80,"cpu"];'],
      ),
      lesson(
        '04-03',
        'Readonly',
        'readonly 限制透過這個型別修改欄位；不代表深層凍結。ReadonlyArray<T> 或 readonly T[] 限制陣列修改方法。',
        'interface Config { readonly id: number; name: string; }',
        '定義 Config 的 id 為唯讀 number、name 為 string。建立 config，id 是 1、name 是 "Lab"。',
        'interface Config { id: number; name: string; }\nconst config: Config = {id:0,name:""};',
        'interface Config { readonly id: number; name: string; }\nconst config: Config = {id:1,name:"Lab"};',
        [test('設定內容', 'config', { id: 1, name: 'Lab' })],
        'config.name = "Lab";',
        ['config.id = 2;'],
      ),
      lesson(
        '04-04',
        '結構型別',
        '相容性通常取決於 shape。含額外欄位的既有物件可傳給只需要部分欄位的函式；直接傳 object literal 可能觸發額外屬性檢查。',
        'function nameOf(x: {name: string}) { return x.name; }\nconst full = {name:"Ada", age:30};\nnameOf(full);',
        '讓 nameOf 接受任何具有 name: string 的物件，回傳 name；不要要求額外欄位。',
        'function nameOf(value: {name: string; age: number}): string {\n  return "";\n}',
        'function nameOf(value: {name: string}): string { return value.name; }',
        [
          test('只提供必要欄位', 'nameOf({name:"Ada"})', 'Ada'),
          test(
            '接受有額外欄位的變數',
            '(()=>{const x={name:"Lin",age:30};return nameOf(x);})()',
            'Lin',
          ),
        ],
        'nameOf({name:"Ada"});',
        ['nameOf({name:123});'],
      ),
    ],
  },
  {
    title: 'Union 與型別縮小',
    subtitle: '把可能性寫進型別。',
    comparisons: {
      'C++':
        'Union 更接近 std::variant 而非 C union。根據 typeof 或 discriminant 分支，編譯器會縮小可用型別。',
      'C#': '可以把 discriminated union 視為以 tag 區分的資料分支。switch 中的 never 能在新增 variant 後提醒你補齊分支。',
      Python:
        '類似 str | int 搭配 isinstance，但 TS 會追蹤控制流程，縮小分支內的型別。',
    },
    lessons: [
      lesson(
        '05-01',
        'typeof 縮小',
        'union 型別只能直接使用所有成員共通的操作。typeof 檢查會讓分支內的值縮小為對應的 primitive 型別。',
        'if (typeof value === "string") { value.toUpperCase(); }',
        '完成 normalize：字串轉大寫，數字用 toFixed(1)。',
        'function normalize(value: string | number): string {\n  return "";\n}',
        'function normalize(value: string | number): string {\n  return typeof value === "string" ? value.toUpperCase() : value.toFixed(1);\n}',
        [
          test('字串分支', 'normalize("hello")', 'HELLO'),
          test('數字分支', 'normalize(3)', '3.0'),
        ],
      ),
      lesson(
        '05-02',
        'Literal union',
        '把合法值列成字串 literal union，可避免任意字串。這些型別不會產生 enum 的執行時物件。',
        'type Mode = "read" | "write";',
        '定義 Mode，只能是 "read" 或 "write"。完成 canWrite。',
        'type Mode = string;\nfunction canWrite(mode: Mode): boolean { return false; }',
        'type Mode = "read" | "write";\nfunction canWrite(mode: Mode): boolean { return mode === "write"; }',
        [
          test('寫入模式', 'canWrite("write")', true),
          test('讀取模式', 'canWrite("read")', false),
        ],
        'type M = Expect<Equal<Mode,"read" | "write">>;',
        ['canWrite("delete");'],
      ),
      lesson(
        '05-03',
        'Discriminated union',
        '讓各分支具有共同的 literal 欄位，便能用它識別分支。不要把所有欄位都改成 optional，否則型別無法表達欄位之間的關係。',
        'type Result = {ok:true; data:string} | {ok:false; error:string};',
        '完成 unwrap：成功回傳 data，失敗回傳 "Error: " 加上 error。',
        'type Result = {ok:true; data:string} | {ok:false; error:string};\nfunction unwrap(result: Result): string { return ""; }',
        'type Result = {ok:true; data:string} | {ok:false; error:string};\nfunction unwrap(result: Result): string { return result.ok ? result.data : `Error: ${result.error}`; }',
        [
          test('成功分支', 'unwrap({ok:true,data:"ready"})', 'ready'),
          test(
            '失敗分支',
            'unwrap({ok:false,error:"offline"})',
            'Error: offline',
          ),
        ],
      ),
      lesson(
        '05-04',
        'Never 與完整分支',
        'never 表示不可能出現的值。完整處理 union 後，剩餘分支可賦值給 never；漏掉任何 variant 都會出現型別錯誤。',
        'function assertNever(x: never): never { throw new Error(String(x)); }',
        '補齊 stateLabel 的 loading 分支，回傳 "Loading"。保留 never 完整性檢查。',
        'type State = "idle" | "loading" | "done";\nfunction stateLabel(state: State): string {\n  switch(state) {\n    case "idle": return "Idle";\n    case "done": return "Done";\n    default: { const impossible: never = state; return impossible; }\n  }\n}',
        'type State = "idle" | "loading" | "done";\nfunction stateLabel(state: State): string {\n  switch(state) {\n    case "idle": return "Idle";\n    case "loading": return "Loading";\n    case "done": return "Done";\n    default: { const impossible: never = state; return impossible; }\n  }\n}',
        [
          test('loading 分支', 'stateLabel("loading")', 'Loading'),
          test('其他分支', '[stateLabel("idle"),stateLabel("done")]', [
            'Idle',
            'Done',
          ]),
        ],
      ),
    ],
  },
  {
    title: '處理未知資料',
    subtitle: '相信驗證，不靠斷言。',
    comparisons: {
      'C++':
        'unknown 不讓你直接操作內容，必須先檢查。as 不會轉換資料，並不是把字串解析為數值的 cast。',
      'C#': 'as 在 TS 只是型別斷言，不像 C# as 執行時檢查失敗會回傳 null。要驗證 JSON 內容，仍需 runtime guard。',
      Python:
        'type annotation 和 cast 都不會驗證真實資料。unknown 強制先縮小型別，避免把未驗證的 JSON 當可信任值。',
    },
    lessons: [
      lesson(
        '06-01',
        'Unknown',
        'any 會繞過多數型別檢查，unknown 則要求先驗證再操作。對外部輸入優先使用 unknown。',
        'function lengthOf(x: unknown) {\n  return typeof x === "string" ? x.length : 0;\n}',
        '完成 safeUpper：字串轉大寫，其餘值回傳空字串。',
        'function safeUpper(value: unknown): string {\n  return value.toUpperCase();\n}',
        'function safeUpper(value: unknown): string {\n  return typeof value === "string" ? value.toUpperCase() : "";\n}',
        [
          test('字串輸入', 'safeUpper("safe")', 'SAFE'),
          test('非字串輸入', 'safeUpper(42)', ''),
          test('null', 'safeUpper(null)', ''),
        ],
      ),
      lesson(
        '06-02',
        'Type guard',
        '回傳型別 value is User 是 type predicate，告訴編譯器 true 時的型別。檢查必須與宣告一致；typeof null 是 object，所以要排除 null。',
        'function isString(x: unknown): x is string {\n  return typeof x === "string";\n}',
        '完成 isUser：非 null 物件且 name 是 string 才通過。',
        'interface User {name: string}\nfunction isUser(value: unknown): value is User {\n  return true;\n}',
        'interface User {name: string}\nfunction isUser(value: unknown): value is User {\n  return typeof value === "object" && value !== null && "name" in value && typeof value.name === "string";\n}',
        [
          test('合法物件', 'isUser({name:"Ada"})', true),
          test('錯誤欄位', 'isUser({name:1})', false),
          test('null 不通過', 'isUser(null)', false),
          test('缺少欄位', 'isUser({})', false),
        ],
        'declare const input: unknown; if(isUser(input)){const name: string = input.name;}',
      ),
      lesson(
        '06-03',
        'As 不會轉換',
        'as number 不會把字串變成數字。使用 Number(...) 執行轉換，再用 Number.isFinite 排除 NaN 或 Infinity。',
        'const number = Number("42"); // 真正的執行時轉換',
        '完成 parseNumber：接受非空字串，轉成有限數值；其他輸入回傳 null。',
        'function parseNumber(value: unknown): number | null {\n  return value as number;\n}',
        'function parseNumber(value: unknown): number | null {\n  if(typeof value !== "string" || value.trim() === "") return null;\n  const result = Number(value);\n  return Number.isFinite(result) ? result : null;\n}',
        [
          test('轉換字串', 'parseNumber("42")', 42),
          test('排除 NaN', 'parseNumber("oops")', null),
          test('拒絕數字輸入', 'parseNumber(42)', null),
          test('排除空字串', 'parseNumber(" ")', null),
          test('排除 Infinity', 'parseNumber("Infinity")', null),
        ],
      ),
      lesson(
        '06-04',
        '安全 JSON 邊界',
        'JSON.parse 的結果不保證形狀正確。把它存為 unknown，再驗證每個需要的欄位，並處理解析例外。',
        'const value: unknown = JSON.parse(text);',
        '完成 readName：合法 JSON 物件的 name 為 string 才回傳 name，其餘回傳 null。',
        'function readName(text: string): string | null {\n  return null;\n}',
        'function readName(text: string): string | null {\n  try {\n    const value: unknown = JSON.parse(text);\n    if(typeof value === "object" && value !== null && "name" in value && typeof value.name === "string") return value.name;\n    return null;\n  } catch { return null; }\n}',
        [
          test('有效資料', 'readName(\'{"name":"Ada"}\')', 'Ada'),
          test('錯誤型別', 'readName(\'{"name":3}\')', null),
          test('無效 JSON', 'readName("{")', null),
          test('null JSON', 'readName("null")', null),
        ],
      ),
    ],
  },
  {
    title: '泛型與型別推導',
    subtitle: '保留輸入與輸出的型別關係。',
    comparisons: {
      'C++':
        'TS 泛型不會像 template 一樣產生各型別的機器碼實例。泛型資訊會被擦除，主要用於檢查值之間的型別關係。',
      'C#': '泛型語法很熟悉，但 TS 的 T 不存在於執行時。keyof / T[K] 能讓回傳型別跟所選物件欄位精確連動。',
      Python:
        '類似 TypeVar，但型別推導和 keyof 能表達物件鍵值之間的精確關係。避免用 unknown 取代本應保留的 T。',
    },
    lessons: [
      lesson(
        '07-01',
        '泛型函式',
        'T 是呼叫時推導的型別參數。輸入 T、回傳 T 能保留關係；改成 unknown 會遺失呼叫端資訊。',
        'function identity<T>(value: T): T { return value; }',
        '完成 first<T>，回傳陣列第一個元素。空陣列回傳 undefined，型別必須表達這個可能性。',
        'function first(values: unknown[]): unknown {\n  return undefined;\n}',
        'function first<T>(values: T[]): T | undefined {\n  return values[0];\n}',
        [
          test('number 陣列', 'first([3,4])', 3),
          test('string 陣列', 'first(["a","b"])', 'a'),
          test('空陣列', 'first([])', undefined),
        ],
        'const n=first([1,2]); const s=first(["a"]); type N=Expect<Equal<typeof n,number|undefined>>; type S=Expect<Equal<typeof s,string|undefined>>;',
      ),
      lesson(
        '07-02',
        '泛型約束',
        'T extends Shape 要求 T 至少符合 Shape，同時保留 T 的其他欄位。直接把參數型別寫成 Shape 會失去額外欄位資訊。',
        'function keep<T extends {id:number}>(value:T):T { return value; }',
        '完成 withName，接受具有 name: string 的物件並原樣回傳，保留完整型別。',
        'function withName(value: {name: string}): {name: string} { return value; }',
        'function withName<T extends {name:string}>(value: T): T { return value; }',
        [
          test('保留欄位', 'withName({name:"Ada",age:30})', {
            name: 'Ada',
            age: 30,
          }),
        ],
        'const result=withName({name:"Ada",age:30}); type A=Expect<Equal<typeof result.age,number>>;',
        ['withName({age:30});'],
      ),
      lesson(
        '07-03',
        'Keyof 與 indexed access',
        'keyof T 是 T 所有可用鍵的 union。K extends keyof T 限制合法欄位，T[K] 回傳該欄位的型別。',
        'type User = {name:string; age:number};\ntype Keys = keyof User; // "name" | "age"\ntype Age = User["age"]; // number',
        '完成 getProperty，能讀取任意物件的合法欄位，推導精確回傳型別，拒絕不存在的鍵。',
        'function getProperty(obj: object, key: string): unknown {\n  return undefined;\n}',
        'function getProperty<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}',
        [
          test(
            '讀取字串',
            'getProperty({name:"Michael",age:30},"name")',
            'Michael',
          ),
          test('讀取數字', 'getProperty({name:"Michael",age:30},"age")', 30),
        ],
        'const user={name:"Michael",age:30}; const n=getProperty(user,"name"); const a=getProperty(user,"age"); type N=Expect<Equal<typeof n,string>>; type A=Expect<Equal<typeof a,number>>;',
        ['getProperty({name:"Michael",age:30},"email");'],
      ),
      lesson(
        '07-04',
        '泛型介面',
        '介面也能有型別參數，讓同一種容器保留不同內容的型別。使用時可以指定 T，或讓泛型函式推導。',
        'interface Box<T> { value:T; }',
        '定義 Box<T> 和 box<T>，把值包成 {value}，保持內容型別。',
        'interface Box {value: unknown}\nfunction box(value: unknown): Box { return {value}; }',
        'interface Box<T> {value:T}\nfunction box<T>(value:T): Box<T> { return {value}; }',
        [
          test('包裝數值', 'box(42)', { value: 42 }),
          test('包裝字串', 'box("TS")', { value: 'TS' }),
        ],
        'const b=box(42); type B=Expect<Equal<typeof b,Box<number>>>;',
      ),
    ],
  },
  {
    title: '型別轉換工具',
    subtitle: '從既有型別衍生新契約。',
    comparisons: {
      'C++':
        '這些工具是編譯期型別運算，不會複製或轉換執行時物件。mapped type 能逐欄位產生新型別。',
      'C#': '常見用途是從 model 衍生 DTO；Pick/Omit 不會在 runtime 刪除欄位，仍須自己建構實際物件。',
      Python:
        '像從 TypedDict 衍生精確的輸入 shape。satisfies 檢查相容性，但通常保留 expression 自己的較精確型別。',
    },
    lessons: [
      lesson(
        '08-01',
        'Partial 與 Pick',
        'Partial<T> 把屬性變可選；Pick<T,K> 只保留指定欄位。可組合它們表達允許局部更新的欄位。',
        'type Patch = Partial<Pick<User, "name" | "email">>;',
        '定義 UserPatch，只允許可選的 name、email，不包含 id。完成 applyPatch。',
        'interface User {id:number; name:string; email:string}\ntype UserPatch = User;\nfunction applyPatch(user: User, patch: UserPatch): User { return user; }',
        'interface User {id:number; name:string; email:string}\ntype UserPatch = Partial<Pick<User,"name" | "email">>;\nfunction applyPatch(user: User, patch: UserPatch): User { return {...user,...patch}; }',
        [
          test(
            '局部更新',
            'applyPatch({id:1,name:"Ada",email:"a@x"},{name:"Lin"})',
            { id: 1, name: 'Lin', email: 'a@x' },
          ),
        ],
        'type P=Expect<Equal<UserPatch,Partial<Pick<User,"name"|"email">>>>;',
        ['const bad: UserPatch={id:2};'],
      ),
      lesson(
        '08-02',
        'Omit 與 ReturnType',
        'Omit<T,K> 排除欄位，ReturnType<typeof fn> 取得函式回傳型別。typeof 在型別位置取得值的靜態型別。',
        'type NewUser = Omit<User,"id">;\ntype Output = ReturnType<typeof createUser>;',
        '定義 NewUser，排除 id。完成 createUser(input,id)，並定義 Created 為函式回傳型別。',
        'interface User {id:number; name:string}\ntype NewUser = User;\nfunction createUser(input: NewUser, id: number): User { return input; }\ntype Created = unknown;',
        'interface User {id:number; name:string}\ntype NewUser = Omit<User,"id">;\nfunction createUser(input: NewUser, id: number): User { return {...input,id}; }\ntype Created = ReturnType<typeof createUser>;',
        [
          test('建立完整資料', 'createUser({name:"Ada"},7)', {
            name: 'Ada',
            id: 7,
          }),
        ],
        'type N=Expect<Equal<NewUser,{name:string}>>; type C=Expect<Equal<Created,User>>;',
      ),
      lesson(
        '08-03',
        'Mapped type 與 Record',
        'Record<K,V> 建立每個鍵都具有 V 型別的物件。mapped type 用 [K in keyof T] 逐欄位轉換。加上 readonly 或 ? 可修改屬性。',
        'type Flags<T> = { [K in keyof T]: boolean };',
        '定義 Flags<T>：把 T 每個欄位的型別改為 boolean。建立 settings，dark 為 true、compact 為 false。',
        'type Flags<T> = T;\nconst settings: Flags<{dark:string;compact:number}> = {dark:"",compact:0};',
        'type Flags<T> = { [K in keyof T]: boolean };\nconst settings: Flags<{dark:string;compact:number}> = {dark:true,compact:false};',
        [test('旗標值', 'settings', { dark: true, compact: false })],
        'type F=Expect<Equal<Flags<{a:string;b:number}>,Record<"a"|"b",boolean>>>;',
      ),
      lesson(
        '08-04',
        'As const 與 satisfies',
        'as const 保留 literal 型別並讓物件屬性在型別上唯讀。satisfies 檢查符合某型別，同時保留 expression 的資訊；兩者都不執行 runtime 驗證。',
        'const config = {mode:"dark"} as const satisfies {mode:"dark"|"light"};',
        '讓 routes 保持精確 literal 型別，且符合 Record<string, `/${string}`>。home 為 "/"、user 為 "/users"。',
        'const routes: Record<string, string> = {home:"/",user:"/users"};',
        'const routes = {home:"/",user:"/users"} as const satisfies Record<string, `/${string}`>;',
        [test('路由內容', 'routes', { home: '/', user: '/users' })],
        'type H=Expect<Equal<typeof routes.home,"/">>; type U=Expect<Equal<typeof routes.user,"/users">>;',
        ['routes.home = "/other";'],
      ),
    ],
  },
  {
    title: 'Class 與模組',
    subtitle: '把程式組織成可重用單位。',
    comparisons: {
      'C++':
        'TS class 走 JS 原型機制。private 是型別檢查限制，#field 才是 JS 執行時私有欄位。模組 import/export 與 C++ header 不同。',
      'C#': 'constructor(private value: number) 同時宣告欄位與賦值。implements 只做編譯期檢查，不會自動改變方法參數的推導。',
      Python:
        'this 必須明確使用；模組以 export 公開成員、import 引用。import type 只用於型別，轉成 JS 時會移除。',
    },
    lessons: [
      lesson(
        '09-01',
        'Class 與 constructor',
        'class 中用 this 存取欄位。建構子參數加 public/private/readonly 會建立 parameter property 並自動賦值。',
        'class User { constructor(public name: string) {} }',
        '完成 Counter，private value 初始值預設 0，increment 加一並回傳新值。',
        'class Counter {\n  constructor(private value = 0) {}\n  increment(): number { return 0; }\n}',
        'class Counter {\n  constructor(private value = 0) {}\n  increment(): number { return ++this.value; }\n}',
        [
          test('預設初始值', 'new Counter().increment()', 1),
          test(
            '保持物件狀態',
            '(()=>{const c=new Counter(5);c.increment();return c.increment();})()',
            7,
          ),
        ],
        '',
        ['new Counter().value;'],
      ),
      lesson(
        '09-02',
        'Implements',
        'implements 檢查 class 是否符合介面，不會提供實作。方法仍需自行寫型別註記。介面只用於編譯期。',
        'interface Formatter {format(value:string):string}\nclass Upper implements Formatter {\n  format(value:string){return value.toUpperCase();}\n}',
        '完成 PrefixFormatter，實作 Formatter，用 constructor 設定的 prefix 加上輸入字串。',
        'interface Formatter {format(value:string):string}\nclass PrefixFormatter implements Formatter {\n  constructor(private prefix: string) {}\n  format(value:string): string { return value; }\n}',
        'interface Formatter {format(value:string):string}\nclass PrefixFormatter implements Formatter {\n  constructor(private prefix: string) {}\n  format(value:string): string { return this.prefix + value; }\n}',
        [
          test(
            '格式化字串',
            'new PrefixFormatter("[TS] ").format("ready")',
            '[TS] ready',
          ),
        ],
      ),
      lesson(
        '09-03',
        'Import 與 export',
        '檔案使用 import/export 後就成為模組。named export 必須以對應名稱引入。此題提供唯讀的 math.ts 模組，可在編輯器上方查看。',
        '// math.ts\nexport const double = (n:number) => n*2;\n// exercise.ts\nimport { double } from "./math";',
        '從 ./math 匯入 double，完成 quadruple(n)，呼叫 double 兩次。',
        '// 從 ./math 匯入 double\nexport function quadruple(n: number): number { return n; }',
        'import { double } from "./math";\nexport function quadruple(n: number): number { return double(double(n)); }',
        [
          test('模組函式組合', 'quadruple(3)', 12),
          test('負數', 'quadruple(-2)', -8),
        ],
      ),
      lesson(
        '09-04',
        'Import type',
        'import type 明確表示只需要型別，產生 JavaScript 時整段移除。執行時需要的函式或 class 值則必須一般 import。',
        'import type { User } from "./models";',
        '從 ./models 匯入 User 型別，完成 userLabel，回傳 "1: Ada" 格式。',
        '// 匯入 User 型別\nexport function userLabel(user: User): string { return ""; }',
        'import type { User } from "./models";\nexport function userLabel(user: User): string { return `${user.id}: ${user.name}`; }',
        [test('使用模組型別', 'userLabel({id:1,name:"Ada"})', '1: Ada')],
        '',
        ['userLabel({id:"1",name:"Ada"});'],
      ),
    ],
  },
  {
    title: '非同步與整合',
    subtitle: '用型別串起非同步資料流。',
    comparisons: {
      'C++':
        'Promise 表示未来完成或失敗的值；await 暫停 async 函式，不阻塞整個 JS 執行緒。',
      'C#': 'Promise<T> 類似 Task<T>，但 JS 的 async 函式不代表新增執行緒。Promise.all 類似 Task.WhenAll。',
      Python:
        '呼叫 JS async 函式就開始執行並回傳 Promise；不完全等同 Python 建立 coroutine 後才由事件迴圈排程的語意。',
    },
    lessons: [
      lesson(
        '10-01',
        'Promise 與 await',
        'async 函式總是回傳 Promise。await 取得 fulfilled 的值，rejection 會像 throw 一樣進入 catch。',
        'async function value(): Promise<number> { return 42; }',
        '完成 doubled，await 輸入的 Promise<number>，再乘以 2。',
        'async function doubled(input: Promise<number>): Promise<number> {\n  return 0;\n}',
        'async function doubled(input: Promise<number>): Promise<number> {\n  const value = await input;\n  return value * 2;\n}',
        [test('等待 Promise 再計算', 'await doubled(Promise.resolve(21))', 42)],
        'type D=Expect<Equal<ReturnType<typeof doubled>,Promise<number>>>;',
      ),
      lesson(
        '10-02',
        'Promise.all',
        'Promise.all 等待所有 Promise 完成，結果順序跟輸入一致。任何一個 reject 就會 reject，不會自動取消其他工作。',
        'const [user, tasks] = await Promise.all([loadUser(), loadTasks()]);',
        '完成 sumAsync，同時等待所有輸入 Promise，回傳數值總和。',
        'async function sumAsync(inputs: Promise<number>[]): Promise<number> { return 0; }',
        'async function sumAsync(inputs: Promise<number>[]): Promise<number> {\n  const values = await Promise.all(inputs);\n  return values.reduce((a,b) => a+b,0);\n}',
        [
          test(
            '多個結果',
            'await sumAsync([Promise.resolve(2),Promise.resolve(5)])',
            7,
          ),
          test('空集合', 'await sumAsync([])', 0),
        ],
      ),
      lesson(
        '10-03',
        '錯誤處理',
        'strict 模式的 catch 值是 unknown。用 instanceof Error 驗證後再讀取 message；throw 也可以丟出非 Error 值。',
        'try { await work(); } catch(error) {\n  return error instanceof Error ? error.message : "Unknown error";\n}',
        '完成 safeRun，成功回傳結果，Error 失敗回傳其 message，其他失敗回傳 "Unknown error"。',
        'async function safeRun(work: () => Promise<string>): Promise<string> {\n  return work();\n}',
        'async function safeRun(work: () => Promise<string>): Promise<string> {\n  try { return await work(); }\n  catch(error) { return error instanceof Error ? error.message : "Unknown error"; }\n}',
        [
          test('成功', 'await safeRun(async()=>"ok")', 'ok'),
          test(
            'Error',
            'await safeRun(async()=>{throw new Error("offline");})',
            'offline',
          ),
          test(
            '非 Error',
            'await safeRun(async()=>{throw 42;})',
            'Unknown error',
          ),
        ],
      ),
      lesson(
        '10-04',
        '整合：有型別的 client',
        '整合 async、unknown、驗證、discriminated union。網路資料必須在邊界驗證後才轉成領域物件；本題注入模擬 load，不需真實服務。',
        'type Result<T> = {ok:true;data:T} | {ok:false;error:string};',
        '完成 fetchUser(load)：驗證結果具有 number id 與 string name；格式錯誤回傳 Invalid user，載入失敗回傳 Load failed。',
        'interface User {id:number;name:string}\ntype Result<T> = {ok:true;data:T}|{ok:false;error:string};\nasync function fetchUser(load:()=>Promise<unknown>):Promise<Result<User>> {\n  return {ok:false,error:"TODO"};\n}',
        'interface User {id:number;name:string}\ntype Result<T> = {ok:true;data:T}|{ok:false;error:string};\nasync function fetchUser(load:()=>Promise<unknown>):Promise<Result<User>> {\n  try {\n    const x = await load();\n    if(typeof x === "object" && x !== null && "id" in x && typeof x.id === "number" && "name" in x && typeof x.name === "string") {\n      return {ok:true,data:{id:x.id,name:x.name}};\n    }\n    return {ok:false,error:"Invalid user"};\n  } catch {return {ok:false,error:"Load failed"};}\n}',
        [
          test('合法資料', 'await fetchUser(async()=>({id:1,name:"Ada"}))', {
            ok: true,
            data: { id: 1, name: 'Ada' },
          }),
          test(
            '欄位型別錯誤',
            'await fetchUser(async()=>({id:"1",name:"Ada"}))',
            { ok: false, error: 'Invalid user' },
          ),
          test('null 資料', 'await fetchUser(async()=>null)', {
            ok: false,
            error: 'Invalid user',
          }),
          test(
            '載入失敗',
            'await fetchUser(async()=>{throw new Error("network");})',
            { ok: false, error: 'Load failed' },
          ),
        ],
      ),
    ],
  },
];
export const modules = {
  '/math.ts': 'export const double = (n: number): number => n * 2;',
  '/models.ts': 'export interface User { id: number; name: string; }',
};
export const lessons = chapters.flatMap((chapter, chapterIndex) =>
  chapter.lessons.map((lesson, index) => ({ ...lesson, chapterIndex, index })),
);
